# 산포통계

In [1]:
import numpy as np
from scipy import stats
import pandas as pd

## 분산계산

In [6]:
x = [1,2,3,4,5]
print(np.var(x, ddof = 1))
print("-"*20)
print(np.array(x).var())
print("-"*20)
print(pd.Series(x).var(ddof = 0))

2.5
--------------------
2.0
--------------------
2.0

## 표준편차 계산

In [10]:
x = [1,2,3,4,5]
print(np.std(x, ddof = 1))
print("-"*20)
print(np.array(x).std(ddof = 0))
print("-"*20)
print(pd.Series(x).std(ddof = 1))

1.5811388300841898
--------------------
1.4142135623730951
--------------------
1.5811388300841898

## 변동계수의 필요성

In [13]:
# 스케일 영향을 받아서 분사과 표준편차가 상대적 산포를 보여주는데 부적합

x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

print(np.std(x1, ddof = 1))
print(np.std(x2, ddof = 1))

1.5811388300841898
15.811388300841896

In [17]:
# 변동계수 = 표준편차 / 평균

print(stats.variation(x1))
print(stats.variation(x2))

#변동계수는 두개의 집단이 동일함.

0.47140452079103173
0.4714045207910317

In [20]:
print(np.std(x1, ddof = 1) / np.mean(x1))
print(np.std(x2, ddof = 1) / np.mean(x2))

#자유도가 1인경우 > 샘플데이터로 추출한 값의 변동계수를 계산.

0.5270462766947299
0.5270462766947299

## 스케일링
- 둘 이상의 변수의 값을 상대적으로 비교할 때 사용

In [23]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

print(x1) ; print(x2)

[1 2 3 4 5]
[10 20 30 40 50]

In [25]:
# Standard Scaling
z1 = (x1 - x1.mean()) / x1.std()
z2 = (x2 - x2.mean()) / x2.std()

#각 요소의 편차/표준편차
print(z1)
print(z2)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [26]:
# Min-max Scaling
z1 = (x1 - x1.min()) / (x1.max() - x1.min())
z2 = (x2 - x2.min()) / (x2.max() - x2.min())

print(z1)
print(z2)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]

## 데이터 표준화 하기

### 데이터 프레임 만들기

In [8]:
import pandas as pd

In [38]:
X = pd.DataFrame(
    {"x1" : [1,2,3,4,5],
     "x2" : [10,20,30,40,50]
    }
)

In [39]:
X

   x1  x2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

### scikit learn을 활용한 데이터 표준화하기

In [9]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.7.2-cp310-cp310-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.22.0 in c:\users\admin\miniconda3\envs\eda_env\lib\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.8.0 in c:\users\admin\miniconda3\envs\eda_env\lib\site-packages (from scikit-learn) (1.15.3)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.5.2-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.7.2-cp310-cp310-win_amd64.whl (8.9 MB)
   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   ------------ --------------------------- 2.9/8.9 MB 16.8 MB/s eta 0:00:01
   ------------------ --------------------- 4.2/8.9 MB 10.1 MB/s eta 0:00:01
   ------------------------------------ --- 8.1/8.9 MB 12.6 MB/s eta 0:00:01
   ---------------------------------------- 8.9/8.9 MB 12.8 MB/s  0:00:00
Downloading joblib-1.5.2-py3-none-any.whl (308 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn

   ------------- -------------------------- 1/3 [joblib]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   ---------------------------------------- 3/3 [scikit-learn]

Successfully installed joblib-1.5.2 scikit-learn-1.7.2 threadpoolctl-3.6.0

In [10]:
# !dir 
#! 는 터미널 명령어를 사용하는 실행어.

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 1C12-191A

 C:\google_drive\KPMG_7th_lab\statistics_ex 디렉터리

2025-10-16  오전 09:34    <DIR>          .
2025-10-16  오전 09:34    <DIR>          ..
2025-10-14  오후 04:12             4,895 .gitignore
2025-10-15  오전 11:47    <DIR>          .ipynb_checkpoints
2025-10-14  오후 04:12                39 README.md
2025-10-15  오전 09:26             1,074 test.ipynb
2025-10-15  오전 11:48            11,056 [실습1-1]통계_대표통계.ipynb
2025-10-16  오전 09:34            11,464 [실습1-2]통계_산포통계.ipynb
               5개 파일              28,528 바이트
               3개 디렉터리  419,254,734,848 바이트 남음

In [12]:
# MinMaxScaler를 메모리에 로딩
from sklearn.preprocessing import MinMaxScaler

In [15]:
# MinMaxScaler 객체 생성
scaler = MinMaxScaler()
scaled = scaler.fit_transform(X)

In [16]:
scaled

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])

In [17]:
# docstring 불러오기 : shift + tab
#자동완성 : tab

In [19]:
pd.DataFrame(scaled, columns=['x1', 'x2'])

     x1    x2
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

## 표준정규분포를 따르는 data로 변환

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
st_scaler = StandardScaler()
st_scaled = st_scaler.fit_transform(X)

#fit_transform(X) 에 대해 물어볼 것.

In [22]:
st_scaled

array([[-1.41421356, -1.41421356],
       [-0.70710678, -0.70710678],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356]])

In [23]:
pd.DataFrame(st_scaled, columns=['x1','x2'])

         x1        x2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

## 범위와 사분위 범위 계산하기

In [24]:
# numpy를 사용하여 정규분포를 따르는 랜덤한 데이터 만들기

import numpy as np

In [25]:
y = np.random.normal(100, 20, size = 1000)

In [26]:
# 소문자(x) : 칼럼이 1개일 경우
# 대문자(X) : 칼럼이 2개 이상일 경우

In [28]:
y

array([100.56890318, 141.5368697 ,  92.8244399 , 121.49153546,
        89.80525226,  92.81694898,  88.3717851 , 112.311679  ,
        77.33845833, 101.21075532,  89.82842445,  89.62166581,
        92.7286809 ,  94.52172933,  84.1482591 , 116.35282998,
        77.14688696,  94.44955353,  94.12831804, 114.92622742,
        90.97695224, 105.4074812 , 109.30732733, 116.90781275,
        93.6538421 ,  75.63741227, 112.22828319, 107.07604645,
       113.87532949, 110.19433647, 108.32848253,  68.0912474 ,
       100.06929283,  58.94734228, 105.14810858,  82.07107012,
       144.12256938,  61.51795625,  87.93715305,  91.76951584,
       105.8797572 , 117.48633988, 100.27071227, 111.48734658,
       108.92331112,  89.74814639, 126.4358778 ,  62.44661446,
       132.35370829,  91.71539399,  79.05012059,  63.45004404,
       103.99508902,  99.9426575 , 148.11706733, 112.27020035,
       149.81186815, 104.9787121 ,  88.12013202, 115.05533751,
       101.48275295, 116.96103922, 146.09943309, 124.42654402,
        64.62997858, 111.09124128, 130.55247249,  93.76069963,
        97.05690908, 126.10576624,  68.22635619, 105.16969267,
        99.47413905,  36.99833848,  88.13187614, 118.76320361,
       114.95423969, 138.51652503, 108.68964906,  94.65961218,
        76.97363223,  84.24583633, 106.40173158,  40.92931643,
       106.67037191,  90.81709447,  59.09940896, 112.41697118,
       139.68887598, 105.70808773,  79.92889004,  85.87160139,
        72.01926418,  94.61940955,  94.554887  , 114.13748665,
       121.56631281, 159.59149031,  89.34582389,  80.41728861,
       104.65926647,  61.634097  , 111.43377506,  94.26190446,
        95.11370476,  87.44945984, 133.44812614, 141.43500989,
        70.96857005, 112.20546563, 103.36900291, 104.44354782,
       101.87531445,  98.9781002 ,  65.73762595,  87.43192229,
        85.83846067, 119.01118467,  96.99731507,  97.86110006,
       120.39804072, 120.40187786,  69.04609102,  83.41711568,
        84.59916602, 105.63179492, 149.53844168, 131.30481393,
        98.45635371, 103.47058144,  97.06663236,  97.86820432,
       122.02679075,  63.70673082,  95.17661907, 107.17017738,
       118.82094369,  98.58480999, 117.58761929, 122.70767582,
        93.77505838, 102.12575082, 110.91276876,  99.22618334,
        81.93680978, 103.17834129, 135.18013277,  96.60158165,
       165.3738135 , 146.2141957 ,  74.80342129, 100.19295531,
        97.24354437,  62.80070081, 105.18066301,  85.35919937,
        89.42855827,  89.34971427,  85.74020527, 129.5787358 ,
        81.90149584,  75.04635587,  90.92444579, 118.19278722,
       119.7131234 ,  88.44341447,  80.40231032, 103.90300864,
        60.15542037, 114.92774376, 114.95807018, 116.07394958,
       145.64639157,  72.31524107,  94.512931  , 107.00642411,
       134.26824298,  90.66687102, 120.20269045, 130.24377573,
       119.42878576,  70.38264909, 114.1335537 , 102.40531203,
       119.34049371, 101.59150878,  78.83195519, 102.12795493,
       129.96364368, 106.38893185,  73.08463692,  97.81506845,
       105.30719246, 101.98522347,  83.6342379 ,  91.89166668,
        68.34368896, 100.69516024,  86.89028875,  81.69100216,
        94.91096817, 115.91824708,  67.47264893,  57.26001233,
        68.36809219, 123.50139796,  65.58868169,  82.28897109,
        93.38639415,  86.08233949, 127.44621539, 130.16667648,
       107.01607451,  93.21875531, 125.9892989 , 148.17037674,
        96.0230506 ,  83.52026295,  73.32307415, 105.62171194,
        98.12225237, 113.94173022,  71.89917363,  93.30775783,
       118.89808976,  86.11712175, 106.10241993, 129.18639383,
        93.73640252,  69.04676604, 144.94623088, 125.74703387,
       115.15380866,  82.38164328, 110.63148842,  71.33652601,
       122.52490468, 113.47577589,  93.64761566,  78.68964447,
        72.67664076, 133.81745904,  50.46783015, 121.61054252,
       123.22262014,  95.41272346,  77.84613298,  69.52443971,
        45.95041278, 119.60448813,  92.10818436, 103.41250862,
        98.9775367 ,  90.38614683,  96.595975  , 104.70415401,
        97.82063551,  87.10575664, 122.95903194,  99.65250586,
       113.33673858,  78.44617094, 125.79798315, 130.46338911,
       132.52447351,  82.21005418,  84.99232932, 109.98740069,
        93.76550651, 102.01889159,  85.58319649,  95.01827992,
       110.37388944, 110.57752304, 129.56857651, 116.83041882,
        96.98602607,  75.91787002, 133.58143773,  83.57787866,
        86.82098078, 104.78212152,  64.89459602, 128.96562909,
        90.22890503, 115.26994795,  87.79117985, 116.26660057,
        94.40471762,  75.24393523, 131.90368076,  89.92522779,
       123.13577972, 120.01648984,  97.97264567,  88.52349861,
       108.26511189, 100.99759033,  87.74390247,  65.19491969,
       107.2534632 , 136.19143942,  80.07670486,  93.40542752,
       105.74509077, 125.75934687, 127.11268048,  95.13762884,
       122.80403841,  76.25518343, 100.65721115, 133.75117504,
        65.05348504,  86.46039066, 115.69453449,  85.0063206 ,
       108.22069947, 105.58269665,  84.00208161,  94.35285622,
        69.59821964,  72.27402588, 104.48257983,  86.51059389,
       108.4805973 , 120.34179145, 109.49574817,  87.97951802,
        73.24185104, 104.13994094, 108.68565185,  95.89725076,
       113.86485989,  79.10898171, 119.78861084,  76.89622187,
       118.55004695, 137.60836893,  94.22570177,  70.82188315,
       129.16680945, 119.91972925,  93.79205847,  61.85392956,
       117.62859655, 123.98704047, 105.49699892,  86.84946478,
        97.55862085,  89.2479389 ,  94.09830688,  86.920999  ,
        89.69944578, 108.79001371, 123.39427184, 100.56808296,
       102.10369974,  80.2124021 ,  94.68419372, 106.02044851,
        76.25019693, 112.37494456, 108.68651429, 117.37906464,
        92.69932826,  94.58752065, 139.00160492, 115.13776685,
        77.56016087, 131.70593   ,  93.23262597,  87.73906461,
       126.25245519, 109.03247153,  83.40115732,  55.0785337 ,
        94.72922739, 100.43518466,  99.70499604,  86.10365363,
        99.03906968,  87.11377767,  70.80873662,  64.48499599,
        91.88986943,  78.64449373, 101.70174609, 123.453202  ,
        74.75959713,  85.36968806, 119.53596842, 127.06939984,
        98.3973491 , 100.5671091 , 116.59416741,  74.64111112,
       109.33110497, 124.56799546, 107.75735052,  75.69147435,
        63.97088662,  94.99378277, 108.46230196,  92.45007257,
        78.14005698,  72.5629894 ,  92.77416892,  50.01520726,
        83.83593499,  90.94375401,  94.94116608,  80.0697313 ,
       123.47951645,  96.40810948,  99.48807057,  83.6050398 ,
        58.40053121, 116.15859109,  54.316602  , 122.37339768,
        85.06484221,  81.5777939 , 118.10673844,  85.90786221,
       114.39018526, 112.6305353 , 122.36460087,  83.13516688,
        79.31361419, 113.62986553, 101.77861605, 100.69300376,
       116.50355674,  80.74490853, 102.67272515,  90.33912686,
       109.18230789,  98.06249935,  90.56591856,  87.18443116,
        82.55263494, 109.00600155,  73.4211875 ,  95.98781694,
        90.62982778,  82.16966404, 117.66655295,  73.2241057 ,
       101.68177169,  94.95249417, 121.84978311, 108.36261753,
        79.09189916, 109.38346428, 131.94611905,  71.94330327,
       109.72894526, 102.42418402, 117.17518901, 107.62114875,
       108.66346556, 113.19513822,  97.07214859,  95.38682745,
        81.2873365 , 121.69067194,  57.85502183,  79.96118389,
        84.89768687,  89.03610653,  96.74664931,  63.89935147,
        93.74256072,  92.96643391,  69.81112778, 113.47003301,
        59.13001531, 126.7838667 ,  79.65573138,  60.48571747,
        54.74348555,  58.71001338, 124.09012086, 101.69445012,
       110.32825793,  81.96134313, 102.59058489,  99.4021244 ,
        92.29746285,  90.06732685,  94.7095111 , 115.17498912,
       107.03356918, 120.29462921,  73.73020559, 127.88924246,
        99.96560668, 108.32829539, 140.20322897, 102.38984982,
        84.60234132,  86.91012499,  90.97436992,  74.9279693 ,
       107.97396027, 123.24046695,  73.79672762,  81.06286602,
        73.15903542, 123.87727767, 105.37193077, 100.97542244,
        84.87600646, 102.95170428, 112.10857748,  57.86224538,
       102.97357788,  65.45937857, 121.07259235, 103.17726882,
        89.47561301,  85.09121473,  77.3636135 , 103.2376117 ,
       140.29273697, 135.41450917,  86.08081716, 124.2466765 ,
        60.15523192,  82.35464739,  58.15552478,  78.2794722 ,
        80.87554321, 101.11181562, 125.38296137, 111.33933624,
        90.5936221 ,  97.86080141, 109.39985273, 101.21374469,
       106.10996985, 104.91638912,  85.26087274, 114.49423024,
        61.50382589,  90.18412669, 131.7182004 ,  88.59255988,
       144.45792488,  96.94030487,  88.12018508,  82.33318548,
        97.54445034, 106.56459708,  88.57688709,  97.50993182,
       134.83462346, 148.20329091,  86.30758787, 104.70156861,
        95.95645637,  78.47981058,  82.0894607 ,  44.58418333,
        96.47282627, 103.56390665, 113.54779327,  84.61781149,
        99.40636821, 129.76539032, 104.5002102 , 113.69763457,
       117.12678324,  89.6804718 , 111.84970223, 112.43871815,
       119.7679291 ,  96.65295888, 111.15265839,  91.01045389,
       116.71125837,  76.70314852,  84.75567824, 105.16869562,
        87.94125049,  88.77557581, 136.24823037, 102.66950092,
       114.26992455, 129.40741824, 100.75572268,  98.12074258,
        92.7937415 ,  71.12306361, 123.77260709,  76.05103054,
        99.29782565,  85.33651658, 112.47715651, 118.47711846,
        94.84991856,  93.19790677,  67.32985295,  79.16043891,
       129.31267443, 103.64770164,  69.50165351, 129.9427312 ,
        68.64971889,  79.71596371,  84.3206315 , 109.28724892,
        92.44237015, 111.19381337,  71.78348485,  75.05058033,
        98.65945565,  87.95028257, 103.15852091, 139.65294306,
       106.47793086,  84.6164861 ,  87.04457543,  99.00866269,
       124.20104057,  88.6224183 , 110.99913456, 112.29184095,
       109.7099275 ,  69.303526  ,  82.04189968, 112.84209261,
        96.19016195,  86.25028349,  88.69334638,  72.34012418,
       103.12447011,  78.08579618,  85.33920387,  98.7198006 ,
       128.26385092, 136.21988349,  98.30949014,  89.56859136,
       100.52801462, 112.09360634, 134.95803565, 106.48660887,
        94.06202583,  74.60897837,  86.29090323,  54.60320829,
       105.02933283,  55.93889912,  98.0443743 ,  97.95308304,
        97.37725578, 120.51942635,  78.81984666, 101.23293316,
        72.76430655,  71.38807222, 112.63311777,  99.16190556,
       130.97278096, 115.4031174 , 134.88426237,  91.80899961,
        94.00276062, 110.27340475,  92.89378866,  70.67610557,
        80.86497253,  99.25102996, 130.21258921,  95.32116052,
       114.46228597,  94.32842898, 121.35825505, 113.41242369,
       132.79276145,  95.76205437,  96.93540415, 109.41619132,
       126.86308425,  88.44315587,  98.85703639, 106.2165941 ,
        92.49852919,  73.12106889, 109.4608908 , 151.66235861,
       137.42409311,  53.29794073, 103.49729509,  96.08682765,
       110.45765863,  83.08217732, 105.67793124, 105.66527252,
       135.31155894,  60.42936083, 144.52607803, 119.59785418,
       102.00186263,  87.6020239 ,  81.47029335, 123.05154794,
        98.00910702,  88.25136303,  94.93934167,  96.97405035,
       123.94941541, 100.68449432, 110.29148187, 136.67359648,
       120.260999  ,  99.28327769,  56.85913365,  92.96066147,
       128.90424458,  74.7325773 ,  74.66516914, 125.20044185,
       123.13610586, 107.05882143, 116.66359115, 107.9470204 ,
        68.52922982,  83.63322291,  97.84892164, 121.10873448,
       122.3993981 , 110.06954467,  61.12018189,  95.57205766,
        49.44156925, 101.33743482, 122.47281067, 103.37609991,
        65.26626654, 102.91844493,  85.94115197,  68.72986438,
       102.30752289,  95.868181  , 120.88173837, 105.37509056,
        84.43027712, 120.99389872,  81.22907203,  85.21443443,
       119.17849021,  91.11780511,  49.60004934,  68.90764548,
       112.96862558, 103.49737393, 103.84781002,  96.78310692,
       106.80720957,  62.93051593,  94.56844244, 105.35864835,
        88.90285603, 133.87609013, 105.21230181, 122.46210123,
       113.47995495, 132.44407767,  79.26492004,  82.88165743,
        71.03872998, 104.59970365, 130.16225191,  90.40722175,
        87.39566665,  53.63212321,  98.91706765, 116.40716761,
       105.77756115, 101.46280326, 139.78642549, 100.15404518,
        94.58215264, 117.03338294,  50.88874028,  99.27983619,
       112.36728878, 134.99327922, 126.28095428, 107.5115878 ,
       117.40897352, 140.11076337, 103.4594874 , 103.06120028,
        92.69881638, 114.59876208,  97.76895826,  97.16345437,
        97.40015062,  80.97304155,  63.21624247,  95.90149929,
       105.74850059,  87.64424492,  92.47622547, 110.49034446,
        92.35981961, 125.11797496,  60.37051188,  88.83845595,
       110.89698819, 106.28820095,  84.26432661, 102.95461122,
        95.18132043, 109.37360423,  93.7856482 , 123.41038588,
       109.43909911, 105.01496727,  58.64411536,  86.57866673,
       100.58950126,  84.00765771, 107.05454913,  77.49221849,
       114.95816353, 124.0600539 , 105.14306539, 102.55222793,
       115.95528994,  75.30625302,  62.55160194, 123.25516865,
       128.87983241,  93.00173546,  98.01538554, 117.52476205,
       106.1276551 ,  95.70940628,  69.0921617 ,  77.71732923,
        85.30926193,  97.80144326,  82.23651437,  92.13386175,
       113.93984542, 101.18292023, 107.02721943, 148.15423238,
       102.45081118,  53.00514088, 124.53674078,  97.37126142,
        84.44878374,  92.72640189,  65.46752515, 104.63631541,
        93.7932597 ,  87.53272153, 118.69439878,  97.68794123,
       108.55903308, 113.79060912,  71.73422157, 101.36859133,
       100.17793964, 106.55766215,  82.89627701, 101.21315484,
        73.04359105, 108.22458227, 134.32155258, 123.1054042 ,
       128.05915094, 117.48344476,  81.87891482, 122.0463663 ,
        58.52889515, 105.16144926, 110.18305866,  81.23075609,
       137.17063202, 115.60256196,  80.40607629, 118.12992936,
        71.26669454, 110.52116893, 148.59481094, 109.03036915,
        76.60016259, 109.16712478,  78.97682529,  69.1953314 ,
       117.22903965,  81.86645977,  96.77511701, 161.78016962,
       126.47042417,  76.61041355,  81.66527979, 113.76187095,
       124.30929676,  87.55698618,  74.85215574, 110.91853678,
        79.90098632, 100.32679045, 104.07291444,  93.73921529,
       100.70589442,  88.90076753,  91.34949574,  78.24132555,
        97.96132092,  40.25302618, 114.41383068,  96.2438476 ,
       113.98300137, 121.1878712 ,  92.00912904,  76.16664137,
       118.31729616,  77.73454471, 128.45024354, 114.2444936 ,
       116.84892877,  78.25403221,  93.84188087, 125.61828643,
        92.24585167,  94.20110255, 114.67613922,  78.2946147 ,
       126.50857514, 107.96382223,  83.51182007,  89.74251243,
        98.90649843,  67.1930541 ,  59.78477757,  97.84693944,
        93.80273455,  81.69895393,  71.83094408, 102.36591845,
        86.18821097, 115.82775101, 121.01731192,  95.64679883,
       117.55364473,  67.79578891, 109.86186823,  82.07950619,
        93.06447217,  93.20356048, 102.72561567, 110.29707698,
       132.03849266,  93.1390163 ,  82.32882159,  92.39239422,
        90.28520388,  97.0189116 ,  74.74470895,  83.88849617,
       109.12588779, 100.53126662,  93.61467917, 126.48451858,
       104.76062549,  74.45455865,  87.10570661,  82.89900698,
        94.16926792,  71.28360266,  94.07488016, 111.27506708,
        96.94713845, 131.7643165 , 142.30746549,  93.76766418,
        73.42446199, 118.05469433,  96.4713567 , 114.66235229,
       110.10774908,  85.88452713, 115.66770236, 101.50878897,
       110.45323418,  92.85232463, 126.594985  , 118.93537526,
       117.10815697,  94.56118984,  76.88631205,  63.111524  ])

-m : 문자 셀로 변환
-y : 코드 셀로 변환

In [31]:
# 범위계산, 총 범위
print(np.ptp(y))
print(np.max(y) - np.min(y))

128.37547502198038
128.37547502198038

In [33]:
# median(중앙값)
print(np.median(y))
print(np.quantile(y, 0.5))

98.62213282135426
98.62213282135426

In [34]:
# IQR(3분위 - 1분위)
print(np.quantile(y, 0.75) - np.quantile(y, 0.25))

28.13293668110397

In [35]:
from scipy import stats
#import scipy.stats

In [37]:
print(stats.iqr(y))

28.13293668110397